apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
  
spec:
  selector:
    matchLabels:
      app: go-hpa
  replicas: 1
  template:
    metadata: 
      labels: 
        app: go-hpa
  
    spec:
      containers:
      - name: nginx
        image: biliano/go-hpa:latest
        ports:
        - containerPort: 9000
        resources:
          requests:
            #memory: "100Mi"
            cpu: "50m"
          limits:
            #memory: "200Mi"
            cpu: "100m"
